def build_regen_analysis_prompt(feedback: str, original_brief: dict) -> str:
    return (
        f"You are an expert content director analyzing reviewer feedback. "
        f"The reviewer rejected a social media post and provided this feedback:\n\n"
        f"'{feedback}'\n\n"
        f"The ORIGINAL brief was:\n"
        f"Hook: {original_brief.get('hook', '')}\n"
        f"Key message: {original_brief.get('key_message', '')}\n"
        f"Emotional angle: {original_brief.get('emotional_angle', '')}\n"
        f"Visual direction: {original_brief.get('visual_direction', '')}\n"
        f"CTA: {original_brief.get('cta', '')}\n\n"
        f"Based on the feedback, decide what should change in the brief. "
        f"Be specific - rewrite the elements the feedback affects, keep the rest as-is.\n\n"
        f"Return ONLY a valid JSON object with these exact fields:\n"
        f"- adjusted_hook (string) - new hook reflecting feedback, or the original if no change is needed\n"
        f"- adjusted_key_message (string) - new key message, or the original\n"
        f"- adjusted_emotional_angle (string) - new emotional angle, or the original\n"
        f"- adjusted_visual_direction (string) - new visual direction, or the original\n"
        f"- adjusted_cta (string) - new CTA, or the original\n"
        f"- tone_shift (string) - short label for the change, e.g. 'more educational', 'less salesy', 'shorter and punchier'\n"
        f"- summary (string) - one sentence explaining what changed and why\n\n"
        f"Return ONLY the JSON object. No explanation. No markdown."
    )
